### PR TITLE
Fix website builds

### PR DESCRIPTION
**Pull request by LucioFranco**

### CODE REVIEW

**Comment by Xaeroxe** [comment]
Weird, why is this necessary?

**Comment by LucioFranco** [comment]
@Xaeroxe some warnings are spewing too much info that is causing us to hit travis log limits and then they shut down our build. We have not had any updated docs/book for 11 days now. This is a bandaid to fix it until I can find a better solution.

**Comment by Xaeroxe** [comment]
😆 that's amazing. well good fix, thanks

**Comment by LucioFranco** [comment]
though doc builds shouldn't fail since master should always be vaild and those errors should be caught there.

**Comment by LucioFranco** [comment]
I know, I didnt believe it till I read the error message 3 times 🤣

**Pull request merged**
