### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by Moxinilian**
It's finally here for review.

This is a redesign of the website. Hopefully it will be more informative to newcomers.

You can check out a live version of this proposal here:
http://amethyst.scrumbles.uk/

My main concerns right now are the paragraph about the ECS being the fastest (I was very uninspired but needed either text or another screenshot to keep the balance of the layout), so feel free to suggest anything else. I also feel like the homepage is lacking screenshots.

What do you think?

### CODE REVIEW

**Review by Xaeroxe — APPROVED** [review]
Great job!  Thank you!

**Review by ebkalderon — APPROVED** [review]
It's been a while since I've participated directly in Amethyst's development, but I just wanted to pop in to say this new site looks fantastic. Thank you for your work!

**Review by LucioFranco — CHANGES_REQUESTED** [review]
This looks outstanding! I have one small nit pick, on mobile on smaller screens it seems the menu doesn't fit properly. 

image

I personally think that paragraph about the ECS is actually great. So overall I think if you fix this small nit, then this should be good for a merge.

**Comment by Moxinilian** [comment]
Okay apparently this is an issue in Chrome rendering background images differently than Firefox.
I'll work on that. Please note that I couldn't reproduce this issue in Firefox, Edge and Safari, so it's probably only an issue with blink.

**Comment by Moxinilian** [comment]
`#[derive(AngryRant)]`
I fixed the bug. This was because Chrome could not handle SVG files properly, even tho Microsoft Edge does a better job at that.

Feel free to check it works on the website (if it doesn't, please clear your cache, Chrome is pretty aggressive with that).

**Review by LucioFranco — APPROVED** [review]
Sweet, LGTM!!

**Comment by Xaeroxe** [comment]
I propose we merge this prior to 0.8 so that we can work out any kinks in deployment if we need to.  Once we're happy with the deployment let's do 0.8 @jojolepro

**Comment by Moxinilian** [comment]
I have never used Travis before, but I did it so normally it should work out of the box.
Jojo and I discussed about it yesterday, and we think the new website will be ideal to host the upcoming traffic peak caused by the 0.8 release.

**Comment by LucioFranco** [comment]
@Moxinilian we can merge this and any travis issues that arise I can fix, since I originally built a lot of how the site deploys.

**Comment by Moxinilian** [comment]
Also, sorry @LucioFranco for not using cobalt! ahah
I became aware of its existence only a couple days ago.
I believe it would have made deployment a bit easier, but eh.

**Comment by Xaeroxe** [comment]
With that in mind.. let's break things!

bors r+

**Pull request merged**
