### PR TITLE
Address request for RSS feed (issue #106)

### PR DESCRIPTION
**Pull request by zacnomore**
Gutenberg was already generating an rss feed available at [the default url].(https://www.amethyst.rs/rss.xml) This change would add the feed to the top navigation with the label "feed" next to "news."

### CODE REVIEW

**Comment by zacnomore** [comment]
#106

**Review by torkleyy — APPROVED** [review]
Thanks, LGTM!

**Review by Moxinilian — CHANGES_REQUESTED** [review]
I don't think this deserves a full icon in the header bar.
I'd prefer it to replace Gitter in the footer.

**Comment by zacnomore** [comment]
@Moxinilian I've moved it to the footer where the Gitter link was.

**Review by Moxinilian — APPROVED** [review]
Perfect, thank you! I was worried removing Gitter would make it no longer perfectly balanced (like all things normally should be), so this is the ideal replacement.
bors r+

**Pull request merged**
