### PR TITLE
Fix publish date

### PR DESCRIPTION
**Pull request by Xaeroxe**
Woops, I used the old date in this post.  I'm gonna merge this as soon as travis passes with it.

### CODE REVIEW

**Comment by torkleyy** [comment]
bors not activated here?

**Comment by Xaeroxe** [comment]
@torkleyy I just added you.

**Review by Aceeri — COMMENTED** [review]
Going to want to change the file name as well probably.

**Comment by Xaeroxe** [comment]
Nope, that'll break the links we just sent out everywhere.

**Comment by Xaeroxe** [comment]
We could use a redirect, but I'm not sure how to do that in markdown.

**Pull request merged**
