### PR TITLE
Fix a link to master doc instead of latest on landing page

### PR DESCRIPTION
**Pull request by Moxinilian**

### CODE REVIEW

**Review by topokel — APPROVED** [review]

**Comment by topokel** [comment]
bors r=distransient

**Comment by topokel** [comment]
sorry uwu I am not powerful enough

**Comment by khionu** [comment]
"master instead of latest" this PR seems to do the opposite?

**Comment by topokel** [comment]
@khionu the title is saying "Fix that the current link is to master doc instead of the latest"

**Pull request merged**
