### PR TITLE
Revamp documentation page

### PR DESCRIPTION
**Pull request by dotellie**
Preview

Also contains a hack to be able to reference the latest tag in the HTML.

### CODE REVIEW

**Review by LucioFranco — APPROVED** [review]
looks fantastic, thanks.

**Review by Moxinilian — APPROVED** [review]
it fucking suxxxxxxx

**Comment by Moxinilian** [comment]
Could you make all the HTML in the develop book and doc aliases be a redirection to their master counterpart instead? That way develop-based links will die off.

**Comment by Moxinilian** [comment]
Also I think LucioFranco forgot to update the links in get-started.md, could you do that? They need to point to the latest release.

**Comment by Moxinilian** [comment]
I think it should be ready for merging now, I think everybody spat on it as much as they needed.
bors r+

**Pull request merged**
