### PR TITLE
Secondary gitter style fixes

### PR DESCRIPTION
**Pull request by Aceeri**
Changes gitter to a custom style and uses our own since it wouldn't let me just add the gitter styles after the meta tags sadly.

### CODE REVIEW

**Comment by ebkalderon** [comment]
@Aceeri We already have part of the Gitter CSS in [`main.css`](https://github.com/amethyst/website/blob/master/src/css/main.css#L379-L398). Should we:
1. Merge the relevant parts of `main.css` into `gitter.css`?
2. Move everything from `gitter.css` into `main.css`?

**Comment by Aceeri** [comment]
I think it is just easier for everyone if they are separate. `gitter.css` is very long and most of it we wouldn't touch again. We can merge the relevant parts from `main.css` into `gitter.css` though.

**Comment by ebkalderon** [comment]
@Aceeri Sounds good!

**Comment by Aceeri** [comment]
Should be all good now.

**Comment by ebkalderon** [comment]
It works on my laptop. Thanks, @Aceeri. Merged!

**Pull request merged**
