### PR TITLE
Add RSS support for cobalt blog

### PR DESCRIPTION
**Pull request by LucioFranco**
This PR adds simple RSS feed via a `rss.xml` file that is located at `amethyst.rs/rss.xml` for a simple RSS feed. This is connected to issue [#27](https://github.com/ebkalderon/amethyst/issues/27).

### CODE REVIEW

**Comment by ebkalderon** [comment]
@LucioFranco Does the `rss.xml` file link to the WordPress blog or to the Cobalt.rs blog?

**Comment by LucioFranco** [comment]
@ebkalderon It points to `blog.amethyst.rs` but now that I think of it, it should just point to `amethyst.rs`.

**Comment by ebkalderon** [comment]
Well, we could have `blog.amethyst.rs` point to `www.amethyst.rs/blog` eventually, so it might not be necessary to change it yet. But for now, I'm guessing it's pointing at the WordPress blog?

**Comment by LucioFranco** [comment]
Yes it points to the current blog right now.

**Comment by ebkalderon** [comment]
If the WordPress blog were taken down and redirected to Cobalt.rs, would the user see old WordPress posts in the feed?

**Comment by ebkalderon** [comment]
Per our discussion starting on [March 22, 2016 3:44 PM](https://gitter.im/ebkalderon/amethyst?at=56f1a0b6a80ca7f40ae30a5f), we will keep the WordPress site open for a while and make a post on it that notifies users to migrate to the new RSS feed, and all subsequent _TWIA_ posts will be made on Cobalt.rs instead.

With this in mind, I'll gladly merge this pull request. Thanks @LucioFranco!

**Pull request merged**
